import{S as v,a as q,i}from"./assets/vendor-BMHzDZyJ.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const m=document.querySelector(".loader"),g=document.querySelector(".gallery"),f=document.querySelector(".load-more-button"),P=new v(".gallery a",{captionsData:"alt",captionDelay:250});function h(o){const e=o.map(({webformatURL:s,largeImageURL:c,tags:t,likes:r,views:a,comments:b,downloads:E})=>`<li class="gallery-item">
      <a href="${c}">
        <img
          class="gallery-img"
          src="${s}"
          alt="${t}"
        />
      </a>
      <div class="info">
        <p class="info-descr">Likes: ${r}</p>
        <p class="info-descr">Views: ${a}</p>
        <p class="info-descr">Comments: ${b}</p>
        <p class="info-descr">Downloads: ${E}</p>
      </div>
    </li>`).join("");g.insertAdjacentHTML("beforeend",e),P.refresh()}function M(){g.innerHTML=""}function y(){m.classList.remove("hidden")}function p(){m.classList.add("hidden")}function w(){f.classList.remove("hidden")}function l(){f.classList.add("hidden")}const R="https://pixabay.com/api/",$="50309371-d07515f8c9a862bfe72f170ff",L=15;async function S(o,e){try{return(await q.get(R,{params:{key:$,q:o,page:e,per_page:L,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}catch(s){throw console.error("Error fetching images:",s),s}}const x=document.querySelector(".form");document.querySelector(".gallery");document.querySelector(".loader");const A=document.querySelector(".load-more-button");let d,n=1,u=0;function B(){const o=document.querySelector(".gallery-item");if(!o)return;const e=o.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}x.addEventListener("submit",async o=>{if(o.preventDefault(),M(),d=o.target.elements["search-text"].value.trim(),n=1,d===""){i.warning({title:"Attentione",message:"The field cannot be empty!",position:"topRight"}),l();return}y();try{const e=await S(d,n),s=e.hits;if(s.length===0){i.warning({title:"Sorry",message:"There are no images matching your search query. Please try again!",position:"topRight",timeout:3e3}),l();return}h(s),u=Math.ceil(e.totalHits/L),n<u?w():(l(),i.warning({title:"Sorry",message:"We are sorry, but you have reached the end of search results",position:"topRight",timeout:3e3}))}catch(e){i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(e)}finally{p(),o.target.reset()}});A.addEventListener("click",async o=>{n+=1,y();try{const s=(await S(d,n)).hits;h(s),B(),n<u?w():(l(),i.warning({title:"Sorry",message:"We are sorry, but you have reached the end of search results",position:"topRight",timeout:3e3}))}catch(e){i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(e)}finally{p()}});
//# sourceMappingURL=index.js.map
